- name: Disable cloud network config
  ansible.builtin.copy:
    src: 99-disable-network-config.cfg
    dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg

- name: Create network config
  ansible.builtin.template:
    src: 50-ansible.yaml.j2
    dest: /etc/netplan/50-ansible.yaml
  register: network_config

- name: Delete default network config
  ansible.builtin.file:
    path: /etc/netplan/50-cloud-init.yaml
    state: absent

- name: Apply network config
  ansible.builtin.command: netplan apply
  when: network_config.changed
