- name: Rewrite /etc/hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"
