- name: Set reverse DNS entry
  hcloud_rdns:
    api_token: "{{ hcloud_token }}"
    server: "{{ server_name }}"
    ip_address: "{{ item }}"
    dns_ptr: "{{ hostname }}"
    state: present
  with_items:
    - "{{ server.hcloud_server.ipv4_address }}"
    - "{{ server.hcloud_server.ipv6[:-3] + '1' }}"
