- name: Setup hetzner resources
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - hetzner

- name: Apply server configuration
  hosts: servers
  remote_user: root
  vars:
    docker_compose_version: 2.14.1
    mailcow__install_path: "/opt/mailcow-dockerized"
    mailcow__hostname: "{{ hostname }}"
    mailcow__git_version: "{{ mailcow_version }}"
    mailcow__timezone: "{{ timezone }}"
    mailcow__redirect_http_to_https: yes
    mailcow__config_use_watchdog: yes
    mailcow__config_additional_server_names: ["mta-sts.*"]
    mailcow__config_additional_san: ["mta-sts.*"]
  environment:
    BORG_RSH: ssh -o StrictHostKeyChecking=no
  roles:
    - server
    - mailcow
    - mailcow-customized
